<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cooler extends Model
{
    protected $fillable = [
        // Basic outlet information
        'outlet_serial_number',
        'region',
        'city',
        'outlet_name',
        'dc_name',
        'outlet_code_bsdc_lays_code',
        'belongs_to_chain',
        'chain_name',
        'area_name',
        'detailed_address',
        'area_type',
        'area_classification',
        'area_houses_type',
        'next_to',
        'type',
        'classification',
        'size_per_sqm',
        'outlet_photo',
        'geo_location_link',
        'geo_location_lat',
        'geo_location_long',
        'top_shop',
        'signage_written_in',
        'contact_person_name',
        'phone_number',
        'cashier_system_count',
        'delivery_availability',
        'pos_name',
        'butcher_availability',
        'frozen_food_availability',
        'outlet_service',
        'storage_availability',

        // Pepsi Coolers
        'pepsi_coolers',
        'pepsi_single_door_coolers',
        'pepsi_single_door_pictures',
        'pepsi_double_door_coolers',
        'pepsi_double_door_pictures',
        'pepsi_triple_door_coolers',
        'pepsi_triple_door_pictures',
        'pepsi_total_doors',
        'pepsi_prime_location',
        'pepsi_cooler_location',
        'pepsi_foreign_product_availability',
        'pepsi_can_availability',
        'pepsi_nrb_availability',
        'pepsi_pet_availability',

        // Cola Coolers
        'cola_coolers',
        'cola_single_door_coolers',
        'cola_double_door_coolers',
        'cola_triple_door_coolers',
        'cola_cooler_pictures',
        'cola_total_doors',
        'cola_prime_location',
        'cola_cooler_location',
        'cola_can_availability',
        'cola_nrb_availability',
        'cola_pet_availability',

        // Other Brand Coolers
        'rani_single_door_cooler',
        'rani_double_door_cooler',
        'rani_triple_door_cooler',
        'rani_total_doors',
        'nada_single_door_cooler',
        'nada_double_door_cooler',
        'nada_triple_door_cooler',
        'nada_total_doors',
        'karawanchi_single_door_cooler',
        'karawanchi_double_door_cooler',
        'karawanchi_triple_door_cooler',
        'karawanchi_total_doors',
        'rc_single_door_cooler',
        'rc_double_door_cooler',
        'rc_triple_door_cooler',
        'rc_total_doors',
        'alsafi_danon_single_door_cooler',
        'alsafi_danon_double_door_cooler',
        'alsafi_danon_triple_door_cooler',
        'alsafi_danon_total_doors',
        'sinalco_single_door_cooler',
        'sinalco_double_door_cooler',
        'sinalco_triple_door_cooler',
        'sinalco_total_doors',
        'other_juices_brand_name',
        'other_juices_single_door_cooler',
        'other_juices_double_door_cooler',
        'other_juices_triple_door_cooler',
        'other_juices_total_doors',

        // Energy Drinks
        'fireball_single_door_cooler',
        'fireball_double_door_cooler',
        'fireball_triple_door_cooler',
        'fireball_total_doors',
        'redbull_single_door_cooler',
        'redbull_double_door_cooler',
        'redbull_triple_door_cooler',
        'redbull_total_doors',
        'rockstar_single_door_cooler',
        'rockstar_double_door_cooler',
        'rockstar_triple_door_cooler',
        'rockstar_total_doors',
        'predator_single_door_cooler',
        'predator_double_door_cooler',
        'predator_triple_door_cooler',
        'predator_total_doors',
        'smart_single_door_cooler',
        'smart_double_door_cooler',
        'smart_triple_door_cooler',
        'smart_total_doors',
        'asan_single_door_cooler',
        'asan_double_door_cooler',
        'asan_triple_door_cooler',
        'asan_total_doors',
        'red_strong_single_door_cooler',
        'red_strong_double_door_cooler',
        'red_strong_triple_door_cooler',
        'red_strong_total_doors',
        'tiger_single_door_cooler',
        'tiger_double_door_cooler',
        'tiger_triple_door_cooler',
        'tiger_total_doors',
        'white_tiger_single_door_cooler',
        'white_tiger_double_door_cooler',
        'white_tiger_triple_door_cooler',
        'white_tiger_total_doors',
        'other_energy_drink_brand_name',
        'other_energy_single_door_cooler',
        'other_energy_double_door_cooler',
        'other_energy_triple_door_cooler',
        'other_energy_total_doors',

        // Water Coolers
        'life_single_door_cooler',
        'life_double_door_cooler',
        'life_triple_door_cooler',
        'life_total_doors',
        'aquafina_single_door_cooler',
        'aquafina_double_door_cooler',
        'aquafina_triple_door_cooler',
        'aquafina_total_doors',
        'sulymaniyah_single_door_cooler',
        'sulymaniyah_double_door_cooler',
        'sulymaniyah_triple_door_cooler',
        'sulymaniyah_total_doors',
        'lulua_single_door_cooler',
        'lulua_double_door_cooler',
        'lulua_triple_door_cooler',
        'lulua_total_doors',
        'alwaha_single_door_cooler',
        'alwaha_double_door_cooler',
        'alwaha_triple_door_cooler',
        'alwaha_total_doors',
        'masafi_single_door_cooler',
        'masafi_double_door_cooler',
        'masafi_triple_door_cooler',
        'masafi_total_doors',
        'other_water_brand_name',
        'other_water_single_door_cooler',
        'other_water_double_door_cooler',
        'other_water_triple_door_cooler',
        'other_water_total_doors',

        // MALT Coolers
        'barbican_single_door_cooler',
        'barbican_double_door_cooler',
        'barbican_triple_door_cooler',
        'barbican_total_doors',
        'sanabil_single_door_cooler',
        'sanabil_double_door_cooler',
        'sanabil_triple_door_cooler',
        'sanabil_total_doors',
        'other_malt_brand_name',
        'other_malt_single_door_cooler',
        'other_malt_double_door_cooler',
        'other_malt_triple_door_cooler',
        'other_malt_total_doors',

        // Summary fields
        'total_number_of_coolers',
        'open_chiller_availability',
        'open_chiller_length',
        'not_branded_coolers_availability',
        'other_branded_coolers',

        // Snack availability
        'lays_availability',
        'lays_availability_location',
        'lays_blocks',
        'lays_stand',
        'doritos_availability',
        'doritos_availability_location',
        'doritos_blocks',
        'doritos_stand',
        'cheetos_availability',
        'cheetos_availability_location',
        'cheetos_blocks',
        'cheetos_stand',
        'nice_availability',
        'nice_stand',
        'nice_blocks',
        'bato_availability',
        'bato_stand',
        'bato_blocks',
        'pringles_availability',
        'pringles_stand',
        'pringles_blocks',
        'dana_dana_availability',
        'dana_dana_stand',
        'dana_dana_blocks',
        'kish_availability',
        'kish_stand',
        'kish_blocks',

        // Other products
        'battery',
        'biscuits',
        'chocolate',
        'ice_cream',
        'nuts',
        'personal_care',
        'popcorn',
        'rice_pack',
        'tobacco',
    ];

    protected $casts = [
        // Boolean fields
        'top_shop' => 'boolean',
        'delivery_availability' => 'boolean',
        'butcher_availability' => 'boolean',
        'frozen_food_availability' => 'boolean',
        'outlet_service' => 'boolean',
        'storage_availability' => 'boolean',
        'pepsi_prime_location' => 'boolean',
        'pepsi_foreign_product_availability' => 'boolean',
        'pepsi_can_availability' => 'boolean',
        'pepsi_nrb_availability' => 'boolean',
        'pepsi_pet_availability' => 'boolean',
        'cola_prime_location' => 'boolean',
        'cola_can_availability' => 'boolean',
        'cola_nrb_availability' => 'boolean',
        'cola_pet_availability' => 'boolean',
        'open_chiller_availability' => 'boolean',
        'not_branded_coolers_availability' => 'boolean',
        'lays_availability' => 'boolean',
        'lays_stand' => 'boolean',
        'doritos_availability' => 'boolean',
        'doritos_stand' => 'boolean',
        'cheetos_availability' => 'boolean',
        'cheetos_stand' => 'boolean',
        'nice_availability' => 'boolean',
        'nice_stand' => 'boolean',
        'bato_availability' => 'boolean',
        'bato_stand' => 'boolean',
        'pringles_availability' => 'boolean',
        'pringles_stand' => 'boolean',
        'dana_dana_availability' => 'boolean',
        'dana_dana_stand' => 'boolean',
        'kish_availability' => 'boolean',
        'kish_stand' => 'boolean',
        'battery' => 'boolean',
        'biscuits' => 'boolean',
        'chocolate' => 'boolean',
        'ice_cream' => 'boolean',
        'nuts' => 'boolean',
        'personal_care' => 'boolean',
        'popcorn' => 'boolean',
        'rice_pack' => 'boolean',
        'tobacco' => 'boolean',

        // JSON fields for pictures
        'pepsi_single_door_pictures' => 'array',
        'pepsi_double_door_pictures' => 'array',
        'pepsi_triple_door_pictures' => 'array',
        'cola_cooler_pictures' => 'array',

        // Decimal fields
        'size_per_sqm' => 'decimal:2',
        'geo_location_lat' => 'decimal:8',
        'geo_location_long' => 'decimal:8',
        'open_chiller_length' => 'decimal:2',

        // Integer fields
        'pepsi_coolers' => 'integer',
        'cola_coolers' => 'integer',
        'other_branded_coolers' => 'integer',
        'cashier_system_count' => 'integer',
        'pepsi_single_door_coolers' => 'integer',
        'pepsi_double_door_coolers' => 'integer',
        'pepsi_triple_door_coolers' => 'integer',
        'pepsi_total_doors' => 'integer',
        'cola_single_door_coolers' => 'integer',
        'cola_double_door_coolers' => 'integer',
        'cola_triple_door_coolers' => 'integer',
        'cola_total_doors' => 'integer',
        'total_number_of_coolers' => 'integer',
        'lays_blocks' => 'integer',
        'doritos_blocks' => 'integer',
        'cheetos_blocks' => 'integer',
        'nice_blocks' => 'integer',
        'bato_blocks' => 'integer',
        'pringles_blocks' => 'integer',
        'dana_dana_blocks' => 'integer',
        'kish_blocks' => 'integer',
    ];
}
